# BGP max-paths and ecmp
bgp_maximum_paths: 4
bgp_ecmp: 4

# EVPN prevent readvertising routes
overlay_prevent_readvertise_to_server: true

# Adjust default bfd values if desired.
bfd_multihop:
  interval: 5000
  min_rx: 5000
  multiplier: 3

# RD/RT Format
overlay_rd_type:
  admin_subfield: overlay_loopback
overlay_rt_type:
  admin_subfield: 65000
